Repository bbta3-bppt/bams, pull requests merged in 2020-11, with the labels that each got.

#5 Pembaruan dependencies
  .github/release-drafter.yml
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  subscribe.js
Labels: dependencies, maintenance

#7 Update tampilan dependencies dan koreksi minor
  src_backend/query/app.js
  src_backend/query/package-lock.json
  src_backend/query/package.json
  ui/package-lock.json
  ui/package.json
Labels: dependencies, maintenance

#8 ganti endpoint
  ui/src/pages/Query.vue
Labels: maintenance

#9 ganti nama domain ws
  ui/src/pages/Dashboard.vue
Labels: maintenance

#10 Perbaikan isu kompatibilitas versi firebase serta quasar cli v2
  ui/package-lock.json
  ui/package.json
  ui/public/favicon-16x16.png
  ui/public/favicon-32x32.png
  ui/public/icons/apple-icon-152x152.png
  ui/public/icons/icon-128x128.png
  ui/public/icons/icon-192x192.png
  ui/public/icons/icon-256x256.png
  ui/public/icons/icon-384x384.png
  ui/public/icons/icon-512x512.png
  ui/public/icons/ms-icon-144x144.png
  ui/public/quasar-logo.png
  ui/quasar.conf.js
  ui/src/index.template.html
Labels: maintenance

#11 Tambah dokumentasi .env dan ganti endpoint
  README.md
  src_backend/query/helpers/client.js
Labels: documentation, maintenance

#12 Ganti endpoint dengan env dan penyesuaian README
  README.md
  src_backend/query/helpers/database.js
  src_backend/query/package-lock.json
  src_backend/query/package.json
  ui/src/pages/Query.vue
Labels: documentation, maintenance

#13 Oh Wow... modifikasi terapan mqtt client lagi
  src_backend/query/helpers/database.js
  ui/src/pages/Query.vue
Labels: maintenance

#14 tambah catch exception
  ui/src/pages/Query.vue
Labels: maintenance

#15 ubah nama ENV
  src_backend/query/bin/www
Labels: maintenance
